services:
  wg-easy:
    image: 'ghcr.io/wg-easy/wg-easy:latest'
    container_name: wg-easy
    restart: unless-stopped
    environment:
      - WG_HOST=77.77.77.77>>changeme
      - 'PASSWORD_HASH=hashedpassword'
      - 'LANG=en'
      - PORT=8000
      - WG_PORT=51820
      - 'WG_ALLOWED_IPS=0.0.0.0/0, ::/0'
      - 'WG_DEFAULT_DNS=1.1.1.1,8.8.8.8'
    volumes:
      - './wg-easy:/etc/wireguard'
    ports:
      - '51820:51820/udp'
    expose:
      - 8000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8000/"]
      interval: 60s
      timeout: 20s
      retries: 5
      start_period: 60s
      start_interval: 5s
networks:
  proxy:
    external: true
